### ISSUE TITLE
GetGroupBans returns null on success

### ISSUE THREAD

**Issue by dustuu** [vrchatapi/specification#253] opened 2023-07-22 11:51 UTC
Using `GroupsApi.GetGroupBans` will always return null, even when the request seems to succeed with no exceptions thrown or errors logged.

Example code to reproduce the issue (make sure you also log in first, using the sample code from this repo's README):
```csharp
Configuration config = new()
{
    Username = "your_username_here",
    Password = "your_password_here",
    UserAgent = "your_user_agent_here"
};
GroupsApi groupsApi = new(config);
List<GroupMember> groupBans = groupsApi.GetGroupBans("your_group_id_here");
```
Use a group that you own or have role permission to manage bans in.

I have tested the `GET` `groups/{groupId}/bans` endpoint manually with Postman by supplying the exact same user and group info, and confirmed that it works as expected. This issue only occurs for me when using this library.

**Comment by ariesclark** [comment] 2023-07-22 11:55
https://github.com/vrchatapi/specification/blob/d1181faae93f49b270c169410cbd4eafb589afb5/openapi/components/paths/groups.yaml#L177-L179
See the above specification, can make a PR changing this line, should just simply be marked as nullable instead.

**Comment by C0D3-M4513R** [comment] 2024-07-22 13:12
I cannot reproduce this, when manually requesting the bans endpoint.
Tested url: https://vrchat.com/api/1/groups/{groupid}/bans?n=51&offset=0

**Closed** 2024-07-22 20:07 UTC
